---
title: "Olympic Sport Climbing PCA"
author: "Hannah Butler"
date: "8/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
load(file = "2020_olympics.rdata")
```

```{r}
# formatting
# mens data
mens_qual_pca <- mens_quals %>%
  mutate(a = as.numeric(a)
         , b = as.numeric(b)) %>%
  group_by(climber) %>%
  mutate(speed_time = min(a, b, na.rm = TRUE)
         #, bould_zones = as.numeric(substr(results, 3, 3))
         , bould_tops = as.numeric(substr(results, 1, 1)) #+ bould_zones*0.25
         , lead_pos = ifelse(grepl("+", hr, fixed = TRUE), .5, 0)
         , lead_holds = parse_number(hr) + lead_pos
         ) %>%
  ungroup() %>%
  select(climber, speed_time, bould_tops, lead_holds)

# womens data
womens_qual_pca <- womens_quals %>%
  mutate(a = as.numeric(a)
         , b = as.numeric(b)) %>%
  group_by(climber) %>%
  mutate(speed_time = min(a, b, na.rm = TRUE)
         #, bould_zones = as.numeric(substr(results, 3, 3))
         , bould_tops = as.numeric(substr(results, 1, 1)) #+ bould_zones*0.25
         , lead_pos = ifelse(grepl("+", hr, fixed = TRUE), .5, 0)
         , lead_holds = parse_number(hr) + lead_pos
         ) %>%
  ungroup() %>%
  select(climber, speed_time, bould_tops, lead_holds)



womens_qual_pca %>% knitr::kable()
mens_qual_pca %>% knitr::kable()
```

in both mens and womens PCs, the first component can be thought of as "overall ability"

for men, PC2 might be a representation of "power," since it is correlated with # of tops (bouldering typically requires high power moves to reach the top) and speed performance.

```{r}
men_pca <- prcomp(mens_qual_pca[,-1], scale. = TRUE, center = TRUE)
women_pca <- prcomp(womens_qual_pca[,-1], scale. = TRUE, center = TRUE)

men_pca$rotation %>% knitr::kable()
(men_pca$sdev)^2/sum((men_pca$sdev)^2)

plot(men_pca$x[,1], men_pca$x[,2])
text(PC2 ~ PC1, labels=mens_qual_pca$climber,data=men_pca$x, cex=0.5, font=2)

women_pca$rotation %>% knitr::kable()
(women_pca$sdev)^2/sum((women_pca$sdev)^2)

plot(women_pca$x[,1], women_pca$x[,2])
text(PC2 ~ PC1, labels=womens_qual_pca$climber,data=women_pca$x, cex=0.5, font=2)
```