---
title: "An Examination of the Combined Sport Climbing Competition Scoring System"
author: "Hannah Butler"
date: "8/31/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Sport climbing was one of five new sports added to the 2020 Summer Olympics in Tokyo, Japan. There are three competitive disciplines in sport climbing: speed climbing, bouldering, and lead climbing. However, a combined scoring format was chosen due to a limit on medal sets. This combined competition format has been controversial among climbers and enthusiasts, and for good reason. Analysis of combined-climbing competitions and simulations show that there are unexpected consequences of such a system. This is related back to voting systems, where there are clearly violations. First, we characterize some general features of the scoring system calculated with simulation studies and compare these to those of scoring systems used for other combination-style competions. The gist of these characteristics are already known among and have been leveraged among competition climbers to build a winning strategy. More simulations are used to estimate the sensitivity of such a scoring system, which may be used as evidence that even in ideal circumstances, the system is flawed. Finally, analyses of real data from climbing competitions is presented to support the simulations. 